name: CI/CD Pipeline Spring Boot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y empaquetar con Maven
        run: mvn clean package -DskipTests

      - name: Guardar artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy-server1:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Copiar archivo .jar a Server 1 vía SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.NFS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "/home/${{ secrets.NFS_USERNAME }}/app/"
          strip_components: 1

      - name: Ejecutar la aplicación en Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.NFS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.NFS_USERNAME }}/app/
            pkill -f 'java -jar' || true
            nohup java -jar *.jar > app.log 2>&1 &

  deploy-server2:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Copiar archivo .jar a Server 2 vía SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.NFS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "/home/${{ secrets.NFS_USERNAME }}/app/"
          strip_components: 1

      - name: Ejecutar la aplicación en Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.NFS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.NFS_USERNAME }}/app/
            pkill -f 'java -jar' || true
            nohup java -jar *.jar > app.log 2>&1 &